# Generated by Django 3.2.9 on 2021-11-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('music_genre', models.CharField(blank=True, max_length=20)),
                ('DailyPracticeTime', models.TimeField(blank=True)),
                ('Days', models.PositiveIntegerField(blank=True)),
                ('DaysPracticed', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
