# Generated by Django 3.2.9 on 2021-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='DailyPracticeTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='Days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='DaysPracticed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='music_genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
